backend/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.PeopleLoginView.as_view(), name='login'),
    url(r'^logout/$', views.PeopleLogoutView.as_view(), name='logout'),
    url(r'^blogs/$', views.BlogsList.as_view(), name='blogs-list'),
    url(r'^blogs/(?P<id>\d+)/follow/$', views.FollowBlogView.as_view(), name='follow-blog'),

]

backend/people_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^id/', include('posts.urls', namespace='posts')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', TemplateView.as_view(template_name='posts/index.html'), name='index'),
]

backend/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<id>\d+)/create/$', views.PostCreateView.as_view(), name='post-create'),
    url(r'^(?P<id>\d+)/posts/$', views.PostListView.as_view(), name='post-list'),
    url(r'^(?P<id>\d+)/posts/following/$', views.FollowingBlogsPostsView.as_view(), name='following-blogs-posts-list'),
    url(r'^(?P<id>\d+)/posts/following/(?P<slug>[\w-]+)$', views.FollowingBlogPostView.as_view(), name='following-blogs-post-detail'),
    url(r'^(?P<id>\d+)/posts/(?P<slug>[\w-]+)/sign/read$', views.PostSignReadView.as_view(), name='post-sign-read'),
    url(r'^(?P<id>\d+)/posts/(?P<slug>[\w-]+)/$', views.PostDetailView.as_view(), name='post-detail'),
    url(r'^(?P<id>\d+)/posts/(?P<slug>[\w-]+)/update/$', views.PostUpdateView.as_view(), name='post-update'),
    url(r'^(?P<id>\d+)/posts/(?P<slug>[\w-]+)/delete/$', views.PostDeleteView.as_view(), name='post-delete'),
]

backend/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

from posts.models import Post


class UserActivity(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='activity')
    following_blogs = models.ManyToManyField(User, related_name='followed_by')
    read_posts = models.ManyToManyField(Post, related_name='read_by')

backend/posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def get_unique_slug(model, field_name, value):
    max_length = model._meta.get_field(field_name).max_length
    slug = slugify(value)
    num = 1
    unique_slug = '{}-{}'.format(slug[:max_length - len(str(num)) - 1], num)
    while model.objects.filter(** {field_name: unique_slug}).exists():
        unique_slug = '{}-{}'.format(slug[:max_length - len(str(num)) - 1], num)
        num += 1
    return unique_slug


class Post(models.Model):
    blog = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    article = models.TextField(max_length=5000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, max_length=25, blank=True, editable=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self.__class__, 'slug', self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'posts:post-detail',
            kwargs={
                'id': self.blog_id,
                'slug': self.slug,
            }
        )

    def get_delete_url(self):
        return reverse(
            'posts:post-delete',
            kwargs={
                'id': self.blog_id,
                'slug': self.slug,
            }
        )

    def __str__(self):
        return '{author} {title} {date}'.format(
            date=self.created,
            author=self.blog.username,
            title=self.title,
        )

backend/accounts/forms.py
from django.forms import ModelForm

from accounts.models import UserActivity


class ReadPostForm(ModelForm):
    class Meta:
        model = UserActivity
        fields = [
            'read_posts',
        ]


class FollowBlogForm(ModelForm):
    class Meta:
        model = UserActivity
        fields = [
            'following_blogs',
        ]

backend/posts/forms.py
from django.forms import ModelForm

from posts.models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'article',
        ]

backend/accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)

from accounts.forms import ReadPostForm, FollowBlogForm
from accounts.models import UserActivity
from posts.models import Post


class PeopleLoginView(LoginView):
    template_name = 'accounts_login.html'

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse(
                'posts:post-list',
                kwargs={
                    'id': self.request.user.id,
                }
            )


class PeopleLogoutView(LogoutView):
    next_page = reverse_lazy('index')


class FollowBlogView(View):
    def get(self, request, id, *args, **kwargs):
        toggle_user = get_object_or_404(User, id=id)
        if request.user.is_authenticated():
            user_activity, created = UserActivity.objects.get_or_create(user=request.user)
            if toggle_user in user_activity.following_blogs.all():
                user_activity.following_blogs.remove(toggle_user)
            else:
                user_activity.following_blogs.add(toggle_user)
        return redirect('accounts:blogs-list')


class BlogsList(ListView):
    model = User
    template_name = 'blogs_list.html'

backend/posts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)

from accounts.models import UserActivity
from posts.forms import PostForm
from posts.models import Post


class BlogMixin():
    def get_queryset(self):
        queryset = super(BlogMixin, self).get_queryset()
        return queryset.filter(blog=self.kwargs['id'])


class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        form.instance.blog = self.request.user
        return super(PostCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse(
            'posts:post-list',
            kwargs={
                'id': self.kwargs['id'],
            }
        )


class PostListView(BlogMixin, ListView):
    model = Post
    queryset = Post.objects.all()


class FollowingBlogsPostsView(ListView):
    model = Post
    queryset = Post.objects.all()

    def get_queryset(self):
        user = self.request.user
        if not user and not user.id == self.kwargs['id']:
            return None
        queryset = super(FollowingBlogsPostsView, self).get_queryset()
        return queryset.filter(
            blog__in=user.activity.following_blogs.all()
            ).exclude(id__in=user.activity.read_posts.all())


class PostSignReadView(View):
    def get(self, request, slug, id, *args, **kwargs):
        toggle_post = get_object_or_404(Post, slug=slug)
        if request.user.is_authenticated():
            user_activity, created = UserActivity.objects.get_or_create(user=request.user)
            if toggle_post in user_activity.read_posts.all():
                user_activity.read_posts.remove(toggle_post)
            else:
                user_activity.read_posts.add(toggle_post)
            return  HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class FollowingBlogPostView(DetailView):
    model = Post


class PostDetailView(BlogMixin, DetailView):
    model = Post


class PostUpdateView(BlogMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        return self.object.get_absolute_url()


class PostDeleteView(BlogMixin, DeleteView):
    model = Post

    def get_success_url(self):
        return reverse(
            'posts:post-list',
            kwargs={
                'id': self.kwargs['id'],
            }
        )

backend/accounts/templates/accounts_login.html
{% extends 'posts/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="col-md-6 col-md-offset-3">

        <h1>Login</h1>

            <form method="POST" action="">

                {% csrf_token %}

                {{ form.as_p  }}

                <input type="submit" class="btn btn-default"  value="Login">
            </form>
    </div>

{% endblock content %}

backend/accounts/templates/blogs_list.html
{% extends "posts/base.html" %}

{% block head_title %}Blogs list{% endblock head_title %}

{% block content %}

    <div class="col-md-6 col-md-offset-3">

		{% for user in user_list %}
			<div class="thumbnail">
			  <div class="caption">

					<h3>
						<a href="{% url 'posts:post-list' id=user.id %}" >Blog {{ user.username }}</a>
					</h3>
                  <hr/>
                  <p>Followers: {{ user.followed_by.all.count }}</p>
                  <p>
                      <a href="{% url 'accounts:follow-blog' id=user.id %}">Follow</a>
                  </p>

			  </div>
			</div>
		{% endfor %}

   </div>


{% endblock content %}

backend/posts/templates/posts/base.html
<html>
<head>
<title>{% block head_title %}People{% endblock head_title %}
</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"  crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


{% block head_extra %}{% endblock head_extra %}

</head>

<body>


<div class="container-fluid">
    <div class="row">
    <ol class="breadcrumb">
        <li><a href="{% url 'accounts:blogs-list' %}">Blogs</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'posts:post-list' id=request.user.id %}">My Posts</a></li>
            <li><a href="{% url 'posts:post-create' id=request.user.id %}">Create new post</a></li>
            <li><a href="{% url 'posts:following-blogs-posts-list' id=request.user.id %}">Posts Feed</a></li>
        {% endif %}

        {% if not request.user.is_authenticated %}
                <li class="pull-right"><a href="{% url 'accounts:login' %}">Login</a></li>
        {% else %}
                <li class="pull-right">{{ request.user.username }}</li>
                <li class="pull-right"><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% endif %}
    </ol>
    	{% block content %}{% endblock content %}
    </div>
</div>

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

</body>
</html>

backend/posts/templates/posts/index.html
{% extends "posts/base.html" %}

backend/posts/templates/posts/new_post_email.html
<!DOCTYPE html>
<html>
    <head>
        <title>Continue Sign Up</title>
        <meta name="description" content="New post notification">
        <style>
          .email {
            font-size: 14px;
            color: #000000;
          }
          .email-title {
            font-size: 22px;
          }
        </style>
    </head>
    <body>
        <div class="email">
          <h1 class="email-title">{{ post.blog.username }} created new post {{ post.title }}</h1>
          <a href="{% url 'posts:following-blogs-post-detail' slug=post.slug id=followed_by_user.id %}">Visit post page</a>
        </div>
    </body>
</html>

backend/posts/templates/posts/post_confirm_delete.html
{% extends "posts/base.html" %}

{% block content %}

<div class="col-md-6 col-md-offset-3">

    <h1>Confirm Post deletion</h1>

        <form method="POST" action="">

            {% csrf_token %}

            <input type="submit" class="btn btn-default"  value="submit">
        </form>

    {% endblock content %}

</div>

backend/posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}

{% block head_title %}

    {{ post.title }}

{% endblock head_title %}

{% block content %}

    <div class="col-md-6 col-md-offset-3">

        <h1>{{ post.title }} by {{ post.blog.username }}</h1>

        <p>{{ post.article }}</p>
        <p>Post was read: {{ post.read_by.all.count }} times</p>

        {% if request.user.id != post.blog.id %}
            <p><a href="{% url 'posts:post-sign-read' slug=post.slug id=request.user.id %}">Sign Post Read</a> </p>
        {% endif %}
    </div>

{% endblock content %}

backend/posts/templates/posts/post_form.html
{% extends "posts/base.html" %}

{% block content %}

    <div class="col-md-6 col-md-offset-3">

        <h1>Create new post</h1>

            <form method="POST">

                {% csrf_token %}

                {{ form.as_p  }}

                <input type="submit" class="btn btn-default"  value="submit">
            </form>
    </div>

{% endblock content %}

backend/posts/templates/posts/post_list.html
{% extends "posts/base.html" %}

{% block head_title %}Posts list{% endblock head_title %}

{% block content %}

    <div class="col-md-6 col-md-offset-3">

		{% for post in post_list %}
			<div class="thumbnail">
			  <div class="caption">

					<h3>
						<a href="{{ post.get_absolute_url }}" >{{ post.title }}</a> <small>{{ post.created }}</small>
					</h3>

					{% if post.updated %}
						<p> {{ post.updated }} </p>
					{% endif %}

			  </div>
			</div>
		{% endfor %}

   </div>


{% endblock content %}